# Gunakan Python slim
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy source code dan requirements
COPY ./src /app/src
COPY requirements.txt /app/requirements.txt

# Set environment variable 
ENV PYTHONPATH=/app

# Install dependencies
RUN apt-get update && apt-get install -y gcc libssl-dev \
    && pip install --upgrade pip \
    && pip install -r /app/requirements.txt

# Default command 
CMD ["python", "-m", "src.nodes.base_node"]
