version: "3.8"
services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - ds-net

  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      - NODE_ID=node1
      - PORT=5000
      - NODES=node1,node2,node3
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - ds-net

  node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      - NODE_ID=node2
      - PORT=5000
      - NODES=node1,node2,node3
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - ds-net

  node3:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      - NODE_ID=node3
      - PORT=5000
      - NODES=node1,node2,node3
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - ds-net

networks:
  ds-net:
    driver: bridge
